services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - microservices-network

  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Shinjuuichidesu@11"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - microservices-network

  api-gateway:
    image: shinjuuichi/api-gateway:latest
    ports:
      - "5000:8080"
    depends_on:
      - auth-service
      - product-service
      - order-service
    networks:
      - microservices-network

  auth-service:
    image: shinjuuichi/auth-service:latest
    ports:
      - "5001:8080"
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      ConnectionStrings__DefaultConnection: "Server=mssql,1433;Database=UserDb;User Id=sa;Password=Shinjuuichidesu@11;TrustServerCertificate=True"
    networks:
      - microservices-network
    depends_on:
      - mssql

  product-service:
    image: shinjuuichi/product-service:latest
    ports:
      - "5002:8080"
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      ConnectionStrings__DefaultConnection: "Server=mssql,1433;Database=ProductDb;User Id=sa;Password=Shinjuuichidesu@11;TrustServerCertificate=True"
    networks:
      - microservices-network
    depends_on:
      - mssql

  order-service:
    image: shinjuuichi/order-service:latest
    ports:
      - "5003:8080"
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      ConnectionStrings__DefaultConnection: "Server=mssql,1433;Database=OrderDb;User Id=sa;Password=Shinjuuichidesu@11;TrustServerCertificate=True"
    networks:
      - microservices-network
    depends_on:
      - mssql

networks:
  microservices-network:
    driver: bridge

volumes:
  rabbitmq_data:
  mssql_data:
