apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml --out .
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: product-service
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: product-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml --out .
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: product-service
    spec:
      containers:
        - env:
            - name: ConnectionStrings__ProductDb
              value: Server=mssql,1433;Database=ProductDb;User Id=sa;Password=Shinjuuichidesu@11;TrustServerCertificate=True
            - name: MassTransitConfiguration__Host
              value: rabbitmq
            - name: MassTransitConfiguration__Password
              value: guest
            - name: MassTransitConfiguration__Username
              value: guest
          image: shinjuuichi/product-service:latest
          name: product-service
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
